### PR TITLE
Check code in travis

### PR DESCRIPTION
**Pull request by nidico**
Second part of #387.

### CODE REVIEW

**Comment by nidico** [comment]
In order to see whether this works, the temporary branch `2015-12-unbreak-387` and [its travis build](https://travis-ci.org/policycompass/policycompass/builds/95641891) can be looked at instead, as `make` currently fails due to #387.

**Comment by nidico** [comment]
Unfortunately, that branch also fails due to #372.

**Comment by FabiApfelkern** [comment]
@slomo Is this still a valid PR?

**Comment by FabiApfelkern** [comment]
@slomo Do we need this PR?

**Comment by cbotsikas** [comment]
@slomo Do we need this branch? If not, please delete it.

**Pull request closed without merging**
