### PR TITLE
Missing Carneades File, Route for Base URL

### PR DESCRIPTION
**Pull request by FabiApfelkern**

### CODE REVIEW

**Comment by slomo** [comment]
@FabiApfelkern What about the outdates leiningen version in ubuntu LTS? Should we also try to find here a solution.

**Comment by slomo** [comment]
looks fine for me :+1: if you like my changes merge or otherwise remove them

**Comment by FabiApfelkern** [comment]
Have you seen my issue about Carneades: https://github.com/policycompass/policycompass/issues/33
Probably makes things easier for now.

**Comment by slomo** [comment]
I see your point, but I also consider the carneades stuff fixed now.

**Pull request merged**
