### PR TITLE
Add indicator service to frontend config

### PR DESCRIPTION
**Pull request by nidico**

### CODE REVIEW

**Comment by FabiApfelkern** [comment]
Can this be merged, even "All checks failed"?

**Comment by nidico** [comment]
Yeah, the breakage isn't related to this PR.

**Comment by nidico** [comment]
Rebasing as the FCM stage config commit which did't belong here has been moved to a separate PR which is now merged.

**Comment by nidico** [comment]
This is now obsolete as #183 has been merged.

**Pull request closed without merging**
